### ISSUE TITLE
Container is a false dep?

### ISSUE THREAD

**Issue by xenoterracide** [iinteractive/OX#14]
```
  "test" : {
     "requires" : {
        "Container" : "0",
```

so I notice that OX is currently pulling in this as a Test Requires Dep, I suspect this is some dzil foobared and picked up something it should have. because that's in this dist

Fetching http://www.cpan.org/authors/id/W/WI/WILLWOLF/Net-Rackspace-Cloudfiles-0.1.tar.gz ... OK

or am I wrong?

**Comment by doy** [comment]
Oops, thought I caught all of those. Thanks!
