### ISSUE TITLE
OX::RouteBuilder::REST

### ISSUE THREAD

**Issue by domm** [iinteractive/OX#16]
Hi!

While OX::RouteBuilder::HTTPMethod is nice for building small REST-like services, I don't like the fact that I have to set up one controller per action. So I've created OX::RouteBuilder::REST which is basically a mixture of HTTPMethod and ControllerAction.

You can define a Controller Class that contains various actions. To handle HTTP Verb dispatching, the action-methods are postfixed with the HTTP Method (eg item_GET, item_DELETE)

I could't find any nice way to tell parse_action_spec that a given action should use OX:RB:REST, so I choose an ugly one:

```
route '/merchant' => 'REST.ctrl_merchant.root';
route '/merchant/:uuid' => 'REST.ctrl_merchant.item';
```

An alternative solution would be something like
    route '/merchant' => 'ctl_merchant.root', ( REST=>1 );
But this would need some changes in OX internals (pass %params to route_builder_for)
Another alternative would be to use a new keyword ('rest_route'), but I think this would cause even more changes.

You can review the changes here:
https://github.com/domm/OX/commit/1262db9c07fee5ac3f98c9fa58cac135583eddaf
https://github.com/domm/OX/commit/b1b5b1b47ecba47e87a148965af3cc6406cb31af
(a standard github pull request also includes my merge of your changes since my last commit, so it's quite useless..)

So, what do you think? 
Could something like this be included in OX?
Should I release it as a standalone dist? If yes, how can I register OX::RouteBuilder::REST, because it seems that the RouteBuilders have to be hardcoded?

Greetings,
domm

**Comment by doy** [comment]
This all looks reasonable to me. I don't really see the 'REST.foo' thing as being uglier - I think that having the app structure change so drastically based on an extra parameter to `route` would be more confusing. I do want to add more support for making this sort of thing more standardized, but I think what you have here is fine for now. Releasing it to CPAN would be fine - I may decide to fold it into the main dist later, but I do want to clean things up about the way that route builders are handled first, and there's no reason you should have to wait for that to use it. You should be able to register the route builder using something like this:

``` perl
sub import {
    my $caller = caller;
    my $meta = Moose::Util::find_meta($caller);
    $meta->add_route_builder('OX::RouteBuilder::REST');
}
```

That way, just doing `use OX::RouteBuilder::REST` in your app should be sufficient to use it normally. Let me know if this sounds okay to you (and if everything works as you expect).

**Comment by domm** [comment]
ok, I'll do a stand-alone cpan dist then. and thanks for the import-trick to register the builder!

Greetings,
domm
