### ISSUE TITLE
Exception handling in app not working (with new Plack::App::Path::Router::Custom)

### ISSUE THREAD

**Issue by wayan** [iinteractive/OX#17]
Running tests of our OX based application on a fresh machine, we found that exception handling via Plack::Middleware::HTTPExceptions stopped working (sorry for vague description). 

Tracing the code I found that the application created by new Plack::App::Path::Router::Custom 0.07  never fails, instead it returns the exception (see default value for handle_exception).

The problem can be demonstrated with OX tests too - with HTTP::Throwable installed.

```
t/default_middleware.t ............. 1/? Can't call method "request" on an undefined value at /home/danielr/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Test/MockHTTP.pm line 29.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 3.

...
t/http_throwable.t ................. Can't call method "request" on an undefined value at /home/danielr/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Test/MockHTTP.pm line 29.
```

**Comment by genehack** [comment]
Whoops, I got that change into Plack::App::Path::Router and didn't think about the impact on OX. I'll get this fixed ASAP, but in the meantime, if you just downgrade to Plack::App::Path::Router v0.06 things will work.

**Comment by doy** [comment]
Thanks!

**Comment by genehack** [comment]
@doy just released a new version of Plack::App::Path::Router (v0.08) that will resolve this issue. It will hit CPAN soon.

**Comment by genehack** [comment]
@wayan, could you confirm the new Plack::App::Path::Router::Custom release fixed the issues you were seeing?

**Comment by wayan** [comment]
Yes, I could. With the new Plack::App::Path::Router::Custom our tests (as well as the installation of OX) passed. Thank you very much.
