### ISSUE TITLE
wrap middleware with classname not working

### ISSUE THREAD

**Issue by davewood** [iinteractive/OX#18]
DOES NOT WORK (see error msg below)

router as { 
    wrap 'Plack::Middleware::Header' => ( set => [ foo => 'bar' ] );
};

THIS WORKS:

use Plack::Middleware::Header;
my $mw = Plack::Middleware::Header->new( set => [ foo => 'bar' ] );
router as { 
    wrap $mw;
    ...
};

ERROR MSG

Could not find container or service for foo in Mox::Web at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Traversable.pm line 106.
    Bread::Board::Traversable::_get_container_or_service(Mox::Web=HASH(0x54c8ea8), 4) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Traversable.pm line 56
    Bread::Board::Traversable::fetch(Bread::Board::Dependency=HASH(0x5970e90), 4) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Dependency.pm line 44
    Bread::Board::Dependency::__ANON__(Bread::Board::Dependency=HASH(0x5970e90)) called at reader Bread::Board::Dependency::service (defined at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Dependency.pm line 46) line 6
    Bread::Board::Dependency::service(Bread::Board::Dependency=HASH(0x5970e90)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service/WithDependencies.pm line 51
    Bread::Board::Service::WithDependencies::resolve_dependencies(Bread::Board::BlockInjection=HASH(0x5972250)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service/WithDependencies.pm line 39
    Class::MOP::Class:::around(CODE(0x38beb20), Bread::Board::BlockInjection=HASH(0x5972250)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 158
    Class::MOP::Method::Wrapped::**ANON**(Bread::Board::BlockInjection=HASH(0x5972250)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 87
    Bread::Board::BlockInjection::init_params(Bread::Board::BlockInjection=HASH(0x5972250)) called at accessor Bread::Board::BlockInjection::params (defined at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service.pm line 19) line 11
    Bread::Board::BlockInjection::params(Bread::Board::BlockInjection=HASH(0x5972250)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service/WithParameters.pm line 36
    Class::MOP::Class:::before(Bread::Board::BlockInjection=HASH(0x5972250)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 26
    Class::MOP::Method::Wrapped::**ANON**(Bread::Board::BlockInjection=HASH(0x5972250)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 87
    Bread::Board::BlockInjection::get(Bread::Board::BlockInjection=HASH(0x5972250)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service/WithDependencies.pm line 91
    Bread::Board::Service::WithDependencies::try {...} () called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Try/Tiny.pm line 81
    eval {...} called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Try/Tiny.pm line 72
    Try::Tiny::try(CODE(0x5972310), Try::Tiny::Finally=REF(0x58ca058), Try::Tiny::Catch=REF(0x58ca040)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service/WithDependencies.pm line 97
    Bread::Board::Service::WithDependencies::resolve_dependencies(Bread::Board::BlockInjection=HASH(0x59436b8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service/WithDependencies.pm line 39
    Class::MOP::Class:::around(CODE(0x38beb20), Bread::Board::BlockInjection=HASH(0x59436b8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 158
    Class::MOP::Method::Wrapped::**ANON**(Bread::Board::BlockInjection=HASH(0x59436b8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 87
    Bread::Board::BlockInjection::init_params(Bread::Board::BlockInjection=HASH(0x59436b8)) called at accessor Bread::Board::BlockInjection::params (defined at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service.pm line 19) line 11
    Bread::Board::BlockInjection::params(Bread::Board::BlockInjection=HASH(0x59436b8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service/WithParameters.pm line 36
    Class::MOP::Class:::before(Bread::Board::BlockInjection=HASH(0x59436b8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 26
    Class::MOP::Method::Wrapped::**ANON**(Bread::Board::BlockInjection=HASH(0x59436b8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 87
    Bread::Board::BlockInjection::get(Bread::Board::BlockInjection=HASH(0x59436b8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/OX/Meta/Middleware.pm line 104
    OX::Meta::Middleware::resolve(OX::Meta::Middleware=HASH(0x500aa48), Mox::Web=HASH(0x54c8ea8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/OX/Application/Role/Sugar.pm line 49
    Class::MOP::Class:::around(CODE(0x45d9e80), Mox::Web=HASH(0x54c8ea8), Bread::Board::BlockInjection=HASH(0x5503398)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 158
    Class::MOP::Method::Wrapped::**ANON**(Mox::Web=HASH(0x54c8ea8), Bread::Board::BlockInjection=HASH(0x5503398)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 87
    Moose::Meta::Class::**ANON**::SERIAL::21::build_middleware(Mox::Web=HASH(0x54c8ea8), Bread::Board::BlockInjection=HASH(0x5503398)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/OX/Application.pm line 36
    OX::Application::**ANON**(Bread::Board::BlockInjection=HASH(0x5503398)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/BlockInjection.pm line 21
    Bread::Board::BlockInjection::get(Bread::Board::BlockInjection=HASH(0x5503398)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 28
    Class::MOP::Method::Wrapped::**ANON**(Bread::Board::BlockInjection=HASH(0x5503398)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 87
    Bread::Board::BlockInjection::get(Bread::Board::BlockInjection=HASH(0x5503398)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service/WithDependencies.pm line 91
    Bread::Board::Service::WithDependencies::try {...} () called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Try/Tiny.pm line 81
    eval {...} called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Try/Tiny.pm line 72
    Try::Tiny::try(CODE(0x582b710), Try::Tiny::Finally=REF(0x582b890), Try::Tiny::Catch=REF(0x5939bf0)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service/WithDependencies.pm line 97
    Bread::Board::Service::WithDependencies::resolve_dependencies(Bread::Board::BlockInjection=HASH(0x5504238)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service/WithDependencies.pm line 39
    Class::MOP::Class:::around(CODE(0x38beb20), Bread::Board::BlockInjection=HASH(0x5504238)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 158
    Class::MOP::Method::Wrapped::**ANON**(Bread::Board::BlockInjection=HASH(0x5504238)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 87
    Bread::Board::BlockInjection::init_params(Bread::Board::BlockInjection=HASH(0x5504238)) called at accessor Bread::Board::BlockInjection::params (defined at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service.pm line 19) line 11
    Bread::Board::BlockInjection::params(Bread::Board::BlockInjection=HASH(0x5504238)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Service/WithParameters.pm line 36
    Class::MOP::Class:::before(Bread::Board::BlockInjection=HASH(0x5504238)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 26
    Class::MOP::Method::Wrapped::**ANON**(Bread::Board::BlockInjection=HASH(0x5504238)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 87
    Bread::Board::BlockInjection::get(Bread::Board::BlockInjection=HASH(0x5504238)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bread/Board/Container.pm line 159
    Bread::Board::Container::resolve(undef, "service", "App") called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/OX/Application.pm line 112
    OX::Application::to_app(Mox::Web=HASH(0x54c8ea8), HASH(0x54c8cf8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/OX/Application/Role/Sugar.pm line 104
    OX::Application::Role::Sugar::**ANON**(HASH(0x54c8cf8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Middleware/Lint.pm line 24
    Plack::Middleware::Lint::call(Plack::Middleware::Lint=HASH(0x2964be8), HASH(0x54c8cf8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Component.pm line 50
    Plack::Component::**ANON**(HASH(0x54c8cf8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Middleware/StackTrace.pm line 38
    Plack::Middleware::StackTrace::try {...} () called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Try/Tiny.pm line 79
    eval {...} called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Try/Tiny.pm line 72
    Try::Tiny::try(CODE(0x5829ad0), Try::Tiny::Catch=REF(0x5808580)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Middleware/StackTrace.pm line 42
    Plack::Middleware::StackTrace::call(Plack::Middleware::StackTrace=HASH(0x54dbaa8), HASH(0x54c8cf8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Component.pm line 50
    Plack::Component::**ANON**(HASH(0x54c8cf8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Middleware/AccessLog.pm line 24
    Plack::Middleware::AccessLog::call(Plack::Middleware::AccessLog=HASH(0x54c8b18), HASH(0x54c8cf8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Component.pm line 50
    Plack::Component::**ANON**(HASH(0x54c8cf8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Middleware/ContentLength.pm line 10
    Plack::Middleware::ContentLength::call(Plack::Middleware::ContentLength=HASH(0x5820d18), HASH(0x54c8cf8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Component.pm line 50
    Plack::Component::**ANON**(HASH(0x54c8cf8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Util.pm line 142
    eval {...} called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Util.pm line 142
    Plack::Util::run_app(CODE(0x5820c58), HASH(0x54c8cf8)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/HTTP/Server/PSGI.pm line 170
    HTTP::Server::PSGI::handle_connection(HTTP::Server::PSGI=HASH(0x5820ad8), HASH(0x54c8cf8), IO::Socket::INET=GLOB(0x55037a0), CODE(0x5820c58)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/HTTP/Server/PSGI.pm line 129
    HTTP::Server::PSGI::accept_loop(HTTP::Server::PSGI=HASH(0x5820ad8), CODE(0x383a038)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/HTTP/Server/PSGI.pm line 55
    HTTP::Server::PSGI::run(HTTP::Server::PSGI=HASH(0x5820ad8), CODE(0x383a038)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Handler/HTTP/Server/PSGI.pm line 14
    Plack::Handler::HTTP::Server::PSGI::run(Plack::Handler::Standalone=HASH(0x25d9a10), CODE(0x383a038)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Loader/Restarter.pm line 32
    Plack::Loader::Restarter::_fork_and_start(Plack::Loader::Restarter=HASH(0x245af98), Plack::Handler::Standalone=HASH(0x25d9a10)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Loader/Restarter.pm line 89
    Plack::Loader::Restarter::run(Plack::Loader::Restarter=HASH(0x245af98), Plack::Handler::Standalone=HASH(0x25d9a10)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Plack/Runner.pm line 277
    Plack::Runner::run(Plack::Runner=HASH(0x213db10)) called at /home/david/perl5/perlbrew/perls/perl-5.20.1/bin/plackup line 10
 at /home/david/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1/Carp.pm line 167

**Comment by genehack** [comment]
@davewood Try using the `literal` keyword on the value of the `set` param (see https://metacpan.org/pod/OX#literal for docs on `literal`)

**Comment by davewood** [comment]
thank you genehack, this works

```
wrap 'Plack::Middleware::Header' => (
    set => literal(
        [
            'Cache-Control' => 'no-cache, no-store, must-revalidate',
            'Pragma'        => 'no-cache',
            'Expires'       => 0,
        ]
    )
);
```
