### ISSUE TITLE
Suspicious use of fetch in route builders

### ISSUE THREAD

**Issue by wayan** [iinteractive/OX#8]
There is a construction in OX::RouteBuilder::HTTPMethod::compile_routes

```
my $s = $app->fetch($a);
return [
        500,
        [],
        [blessed($app) . " has no service $a"]
] unless $s;
```

which probably doesn't work because fetch raises an exception when the service could not be found. A similar construction is also in OX::RouteBuilder::ControllerMethod.

**Comment by doy** [comment]
Fixed in 87f9202.
